javax.net.ssl.trustStore=C:/OracleWallet/truststore.jks
javax.net.ssl.trustStorePassword=OracleCloud2
javax.net.ssl.trustStoreType=JKS
javax.net.ssl.keyStore=C:/OracleWallet/keystore.jks
javax.net.ssl.keyStorePassword=OracleCloud2
javax.net.ssl.keyStoreType=JKS